<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sora&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styles.css">
    <title>To Do App</title>
</head>
<body>
    <main>
        <div class="container">

            <div class="container">
                <h1>To Do</h1>
            </div>

            <div class="container">
                <?php echo \App\ViewHelpers\AddTaskViewHelper::displayAddTaskForm(); ?>
            </div>

            <div class="container">
                <table class="table table-light">
                    <th>Outstanding Tasks</th>
                    <?php echo \App\ViewHelpers\ViewTaskHelper::displayTasks($tasks); ?>
                </table>
            </div>

        </div>
    </main>
</body>
</html>