<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>To Do App</title>
</head>
<body>
    <main>
        <div class="container">

            <div class="container">
                <h1>To Do List</h1>
            </div>

            <div class="container">
                <?php echo \App\ViewHelpers\AddTaskViewHelper::displayAddTaskForm(); ?>
            </div>

            <div class="container">
                <table class="table table-dark">
                    <th>Incomplete Tasks</th>
                    <?php echo \App\ViewHelpers\ViewTaskViewHelper::displayTasks($tasks); ?>
                </table>
            </div>

        </div>
    </main>
</body>
</html>