<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>To Do App</title>
</head>
<body>
    <main>
        <div class="container">

            <div class="container">
                <h1>To Do List</h1>
            </div>

            <div class="container">
                <form action="/" method="post">
                    <div class="form-group">
                        <input class="form-control" type="text" id="newtask" placeholder="Add new task">
                    </div>
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>

            <div class="container">
                <table class="table table-dark">
                    <th>Incomplete Tasks</th>
                    <?php echo \App\ViewHelpers\ViewTaskViewHelper::displayTasks($tasks); ?>
                </table>
            </div>

        </div>
    </main>
</body>
</html>